export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD'

